language: cpp

compiler:
  - g++
  - clang

os:
  - linux
  - osx

dist: trusty
sudo: required

before_install: Testing/Travis/before_install.sh
script:         Testing/Travis/script.sh

notifications:
  email: false
